---
- name: Setup Apache HTTP Server
  hosts: test
  become: true
  tasks:
    - name: Install httpd package
      dnf:
        name: httpd
        state: present

    - name: Enable httpd service
      systemd:
        name: httpd
        enabled: yes

    - name: Start httpd service
      systemd:
        name: httpd
        state: started

    - name: Configure SELinux to allow httpd on port 80
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Create index.html file
      copy:
        content: "Hello Gondok"
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'
