---
- name: Create Folders and Set Permissions
  hosts: target_servers
  become: true
  vars:
    folders:
      - path: /opt/application
        owner: admin
        group: developers
        mode: '0755'
        subdirs:
          - logs
          - data
          - config
          - temp
      - path: /opt/backup
        owner: backup
        group: backup
        mode: '0700'
        subdirs:
          - daily
          - weekly
          - monthly

  tasks:
    - name: Ensure groups exist
      group:
        name: "{{ item }}"
        state: present
      loop:
        - developers
        - backup

    - name: Ensure users exist
      user:
        name: "{{ item.user }}"
        group: "{{ item.group }}"
        state: present
      loop:
        - { user: 'admin', group: 'developers' }
        - { user: 'backup', group: 'backup' }

    - name: Create parent directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ folders }}"

    - name: Create subdirectories
      file:
        path: "{{ item.0.path }}/{{ item.1 }}"
        state: directory
        owner: "{{ item.0.owner }}"
        group: "{{ item.0.group }}"
        mode: "{{ item.0.mode }}"
      with_subelements:
        - "{{ folders }}"
        - subdirs

    - name: Set special permissions for logs directory
      file:
        path: /opt/application/logs
        state: directory
        mode: '0744'
      when: "'/opt/application/logs' in item.0.path + '/' + item.1"
      with_subelements:
        - "{{ folders }}"
        - subdirs

    - name: Verify permissions are set correctly
      command: "ls -l {{ item.path }}"
      register: ls_output
      changed_when: false
      loop: "{{ folders }}"

    - name: Display folder permissions
      debug:
        msg: "Permissions for {{ item.item.path }}: {{ item.stdout }}"
      loop: "{{ ls_output.results }}"
